name: release for roller
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      actions: read
      contents: write
    steps:
      - id: release-please
        name: Create release notes from conventional commits
        uses: google-github-actions/release-please-action@v3
        with:
          pull-request-header: ":loop: New roller Release"
          release-type: go
          package-name: roller
          prerelease: true
          prerelease-label: beta
          changelog-types: >-
            [

              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"docs","section":"Documentation","hidden":false},
              {"type":"chore","section":"Miscellaneous","hidden":true},
              {"type":"ci","section":"Miscellaneous","hidden":true},
              {"type":"test","section":"Miscellaneous","hidden":true}
            ]
          # token must have repo write permissions ( https://github.com/googleapis/release-please/blob/main/docs/cli.md#create-a-manifest-pull-request-deprecated )
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
        if: steps.release-please.outputs.release_created
        with:
          fetch-depth: '0'

      - name: Set up Go
        uses: actions/setup-go@v5
        if: steps.release-please.outputs.release_created
        with:
          check-latest: true
          go-version-file: go.mod

      - name: Setup release environment
        if: steps.release-please.outputs.release_created
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}' > .release-env

      - name: Release publish
        if: steps.release-please.outputs.release_created
        run: make release
